### ISSUE TITLE
how to add more of the drugs to cornersell.

### ISSUE THREAD

**Issue by Onfyregaming** [Mustachedom/md-drugs#11]
looking to add shatter or lsd tabs to sell while cornerselling cant find where to add them. thanks

**Comment by B0STRA** [comment]
> looking to add shatter or lsd tabs to sell while cornerselling cant find where to add them. thanks

https://github.com/Mustachedom/md-drugs/blob/345f4418a30bb2cf7b34f292dd172f9da395090f/shared/qbdrugsrewrite.lua#L10
You would add whatever drugs you want to corner sell to this file.
