### ISSUE TITLE
map crashing issue

### ISSUE THREAD

**Issue by MamBa-OP** [Mustachedom/md-drugs#16]
when i use that maps it's crashing my game when i try to noclip on pass away legion square ammunation

**Comment by Mustachedom** [comment]
Dont know why it would be crashing you around legion since there is nothing in this script around legion

i havent had any issues reported either of crashing.

**Comment by MamBa-OP** [comment]
not with the script i mean the mlo which are using

**Comment by Mustachedom** [comment]
then remove the mlo? more of an issue for the map creator not me
