### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by BeardedSavage** [Mustachedom/md-drugs#19]
Upon installation I encountered a syntax error following md-drugs/client/travellingmerchant.lua & target.lua. When I dove into the code I noticed that it calls for an "export.qb-target". Not sure if I'm correct or not on this but I don't think the lua likes the "-" in between qb and target. I'm sorry for the bother on this, any help is appreciated. I use all qb besides ps-hud.

**Comment by Mustachedom** [comment]
Hey! I haven't encountered any issues like that with anyone. If you're using qb-target double check your config and make sure Config.Oxtarget is set to false

**Comment by BeardedSavage** [comment]
It is set to false, along with Config.OxInv. There is no config with qb-target.

**Comment by Mustachedom** [comment]
Join the discord linked in the readme and open a ticket, I’ll take a look at everything with you and figure it out

**Comment by BeardedSavage** [comment]
Done

**Comment by Mustachedom** [comment]
fixed: user changed the ox exports to say qb causing error
