### ISSUE TITLE
XTC dosent do anything everything else works tho

### ISSUE THREAD

**Issue by Ristorotta** [Mustachedom/md-drugs#20]
So stealisosafrole, steal mdp2p, makingrawxtc and buying the presses dosent seem to work... however there is no error either

**Comment by Mustachedom** [comment]
are you using the press and third eyeing it?

**Comment by Ristorotta** [comment]
> are you using the press and third eyeing it?

i cant seem to buy the press, do i have to have one to acces the stealing stuff etc?
