### ISSUE TITLE
Attempt to index a nil value "lib"

### ISSUE THREAD

**Issue by MrRaccoon007** [Mustachedom/md-drugs#23]
I have put this into my QB server. When I launch the script I get this error:
![image_2024-02-26_153053545](https://github.com/Mustachedom/md-drugs/assets/161343121/7e69cd3d-bf92-48ab-a221-37594b05c8ce)

Is there an easy fix? i'm not too familiar with this code/script and don't want to mess around and break it, Any support would be great!

Thanks,
Raccoon

**Comment by Mustachedom** [comment]
You need ox_lib and it needs to start before md-drugs
