### ISSUE TITLE
ox target

### ISSUE THREAD

**Issue by djames61** [Mustachedom/md-drugs#25]
hey so ox target does not seem to be working whenever i try to cutcokepowder,cutcoke,bagcoke etc same for meth

**Comment by Mustachedom** [comment]
just downloaded an entirely fresh qb-core build, threw in ox_target, ox_lib, and md-drugs, all working perfect for me. Do you have any errors besides "not seem to be working"

**Comment by djames61** [comment]
> just downloaded an entirely fresh qb-core build, threw in ox_target, ox_lib, and md-drugs, all working perfect for me. Do you have any errors besides "not seem to be working"

Oh I see why it won’t work for me I think it’s bc I’m using a modified QB core by Quasar. I made a test server to see if I could process Coke and it seems to work with OX target because on my main server whenever I use Ox_target I can’t seem to process coke like bag it up etc. do you think that could be the issue for me

**Comment by Mustachedom** [comment]
there could be a couple things not working and with the amount of info i can only make guesses

guess 1) you arent on build number 2944 or above
guess 2) there is some functions that were changed in quasars version of qb-core and I dont know what they changed

**Comment by GodDid1** [comment]
> > just downloaded an entirely fresh qb-core build, threw in ox_target, ox_lib, and md-drugs, all working perfect for me. Do you have any errors besides "not seem to be working"
> 
> Oh I see why it won’t work for me I think it’s bc I’m using a modified QB core by Quasar. I made a test server to see if I could process Coke and it seems to work with OX target because on my main server whenever I use Ox_target I can’t seem to process coke like bag it up etc. do you think that could be the issue for me. Like everything works like I can go get the coke plant I can enter the coke area I just can’t process or bag or cut

you need to look up lol the target shit is above you for some reason 
![image](https://github.com/Mustachedom/md-drugs/assets/162774977/b192ef68-49e2-4140-be1a-36baeb06196a)
