### ISSUE TITLE
all double when entering the server

### ISSUE THREAD

**Issue by Fraprwnt** [Mustachedom/md-drugs#29]
![WhatsApp Image 2024-03-18 at 22 43 23_095b60a6](https://github.com/Mustachedom/md-drugs/assets/58946086/e20da299-de54-4e5d-a953-6b8c7e3e92d0)

when entering the server and the dealer's place everything becomes double, I try to block anything but the result is still double

**Comment by Mustachedom** [comment]
whoops accidently hit close with comment my bad

**Comment by Fraprwnt** [comment]
> whoops accidently hit close with comment my bad
This is in my sql

![image](https://github.com/Mustachedom/md-drugs/assets/58946086/67b82684-57a7-4234-9ed0-9c8f369bea85)

it's still the same, column dealer qb before
