### ISSUE TITLE
Getting this error need help for this!!

### ISSUE THREAD

**Issue by isaadamirr** [Mustachedom/md-drugs#30]
![FiveM_b2944_GTAProcess_9834pMMiCs](https://github.com/Mustachedom/md-drugs/assets/92311797/56431279-34a2-4876-82e9-d8ce30d6c397)

**Comment by Mustachedom** [comment]
either 
A) the items are not in your qb-core/shared/items.lua
B) you have an error in your qb-core/shared/items.lua
C) your config line 15 isnt correct

**Comment by isaadamirr** [comment]
but due to only installing the items, my screen goes all black after multicharacter!

**Comment by Mustachedom** [comment]
then you broke your items.lua 
i rarely check git so i would recommend joining the discord as i will be faster to respond there
