### ISSUE TITLE
Unable to use OX_fuel

### ISSUE THREAD

**Issue by TaakoOfficial** [Mustachedom/md-drugs#31]
`SCRIPT ERROR: @md-drugs/client/oxyruns.lua:26: No such export SetFuel in resource ox_fuel`

Trying to use OX fuel and keep getting this error

**Comment by Mustachedom** [comment]
Ox fuel uses a different export than everyone else, look through their docs and see what their version of setfuel is and change the export

**Comment by TaakoOfficial** [comment]
![chrome_wHLkAZlx7T](https://github.com/Mustachedom/md-drugs/assets/4751889/7cd507d4-d379-45d1-9528-f63a8388d5e5)
This ius all thats in their docs

**Comment by Mustachedom** [comment]
So add the export on the second option and vehicle Id is the spawned car name I think it’s oxycar

**Comment by TaakoOfficial** [comment]
So what exports Entity(oxycar).state.fuel = 100 ?

**Comment by Mustachedom** [comment]
Looks like that should work

**Comment by TaakoOfficial** [comment]
Error parsing script @md-drugs/client/oxyruns.lua in resource md-drugs: @md-drugs/client/oxyruns.lua:26: syntax error near 'Entity'
` exports Entity(oxycar).state.fuel = 100`
