### ISSUE TITLE
To when an ESX version

### ISSUE THREAD

**Issue by Cesartunique912** [Mustachedom/md-drugs#33]
Really liked the preview, but due to my server being on the ESX framework i need to modify the code, but before doing that im just looking to know if there is an ESX version?

**Comment by Mustachedom** [comment]
there is not an esx version, When my ADHD isnt kicking my ass ill try to use bl_bridge to see if i can make a semi working version

**Comment by Cesartunique912** [comment]
okay thx

**Comment by Nickemhatesyou** [comment]
do you happen to have an eta on an ESX version? I attempted to convert and let's just say I wasted 3 hours of my life.
