### ISSUE TITLE
Issue with deliveries.lua

### ISSUE THREAD

**Issue by GrumpyFinster** [Mustachedom/md-drugs#4]
If someone can help me with this issue it would be greatly apprecaited.
![md drugs](https://github.com/Mustachedom/md-drugs/assets/146125685/2b444f21-9b6c-4871-8966-4d7bad0708c6)

CreateThread(function()
    local dealermenu = {}
    if Config.StupidassNewQbItemName then
        for k, v in pairs (QBConfig.ProductsStupidNameRewrite) do 
            dealermenu[#dealermenu + 1] = {
                          icon = "nui://"..Config.imagelink..QBCore.Shared.Items[v.name].image,
                          title = v.label,
                          event = "md-drugs:client:travellingmerchantox",
                          args = {
                              item = v.name,
                              cost = v.price,
                             info = v.info,
                             amount = v.amount,
                            }
                        }
               
                   lib.registerContext({id = 'dealermenu',title = "Dealer Menu", options = dealermenu})
        end           
    else
         for k, v in pairs (QBConfig.Products) do 
            dealermenu[#dealermenu + 1] = {
                          icon = "nui://"..Config.imagelink..QBCore.Shared.Items[v.name].image,
                          title = v.label,
                          event = "md-drugs:client:travellingmerchantox",
                          args = {
                              item = v.name,
                              cost = v.price,
                             info = v.info,
                             amount = v.amount,
                            }
                        }

                   lib.registerContext({id = 'dealermenu',title = "Dealer Menu", options = dealermenu})
        end     
    end
end)

**Comment by Mustachedom** [comment]
What inventory are you using and what is your config.imagelink set to

**Comment by Mustachedom** [comment]
this error comes from the config.imagelink, you need to put your directory in 

for example 

```
ps-inventory/html/images
```

**Comment by Olivergist** [comment]
i'm using ox inventory having the same issue please should i do

**Comment by Mustachedom** [comment]
ox_inventory/web/images

**Comment by Olivergist** [comment]
new error: SCRIPT ERROR: @md-drugs/client/deliveries. lua:59: attempt to index a nil value (global 'ox_inventory')

if i get you correctly i am to change the Config.imagelink to ox_inventory/web/images?  or the whole of ..ox_inventory/web/images..QBCore.Shared.Items[v.name].image, to  ox_inventory/web/images?. thank you for your quick response

**Comment by Mustachedom** [comment]
Just the config option :)

**Comment by Olivergist** [comment]
this QBCore.Shared.Items[v.name].image right?

**Comment by Mustachedom** [comment]
No. The config.imagelink

**Comment by Olivergist** [comment]
@md-drugs/client/deliveries. lua:59: attempt to index a nil value (global 'ox_inventory') this is what is the error i am getting now

**Comment by Mustachedom** [comment]
Join the discord in the readme so we can send pics back and forth and get ya fixed up

**Comment by Olivergist** [comment]
thank you
