### ISSUE TITLE
coke leaf not cutting

### ISSUE THREAD

**Issue by DAnderson-rp** [Mustachedom/md-drugs#40]
![Screenshot 2024-06-16 173640](https://github.com/Mustachedom/md-drugs/assets/173006309/e6853a27-6cf7-48ec-ab1b-98479046cd38)
![Screenshot 2024-06-16 173833](https://github.com/Mustachedom/md-drugs/assets/173006309/478621a8-8aec-4d56-9389-c1d632708ea6)

**Comment by Mustachedom** [comment]
Not an issue, you didn't follow the readme
