### ISSUE TITLE
Emote does not work

### ISSUE THREAD

**Issue by sKyxshadow03** [Mustachedom/md-drugs#45]
I tried Scully emotes, it works but need to cancel the emote everytime after an action, dp and rpemotes does not work when doing an action. Is there a fix for this? I added the emotes action but does not changed anything

**Comment by Mustachedom** [comment]
just pushed an update that should check if you use scully and if you do should cancel properly

**Comment by sKyxshadow03** [comment]
Perfect! Will try this tonight, thank you very much! Also, when using the Heroin table and sell the heroin after, there is no option to sell to certain ped or the only option I have is ''clean it'' is there a fix for this too? Thank you very much! This drug script is the best one in my opinion and it is free!

**Comment by sKyxshadow03** [comment]
There is also this message everytime I do an action


![Screenshot 2024-07-05 185230](https://github.com/Mustachedom/md-drugs/assets/173624286/5d2716d8-7a2a-4f65-85b6-352d36d8f880)

**Comment by Mustachedom** [comment]
fixed in update
