### ISSUE TITLE
coke process

### ISSUE THREAD

**Issue by callums18** [Mustachedom/md-drugs#47]
first stage of coke process starts but doesn't give me anything in return nothing comes up in f8 and the rest of the script works fine  

same for all start processes apart from weed

**Comment by Mustachedom** [comment]
do you have errors?

**Comment by callums18** [comment]
Nah no errors I have everything installed properly like the items and images but it’s always the first stage that give nothing in return after completing

**Comment by Mustachedom** [comment]
does the event in the server look like this

```

RegisterServerEvent('md-drugs:server:makepowder', function(num)
	local src = source
    local Player = QBCore.Functions.GetPlayer(src)
	local playerPed = GetPlayerPed(source)
	if CheckDist(source, playerPed, Config.MakePowder[num]['loc']) then return end
	if not Itemcheck(Player, 'coca_leaf', 1, 'true') then return end
	if Config.TierSystem then		
		local coke = Player.PlayerData.metadata['coke']
		if coke <= Config.Tier1 then
			if RemoveItem("coca_leaf", 1) then AddItem("coke", 1) end
		elseif coke >= Config.Tier1 and coke <= Config.Tier2 then
			if RemoveItem("coca_leaf", 1) then AddItem("cokestagetwo", 1) end
		else
			if RemoveItem("coca_leaf", 1) then AddItem("cokestagethree", 1) end
		end
	else
		if  RemoveItem("coca_leaf", 1) then AddItem("coke", 1) end
	end	
end)

```

**Comment by callums18** [comment]
In what server

**Comment by Mustachedom** [comment]
server/cocaine.lua

**Comment by callums18** [comment]
thats what ive got  
![image](https://github.com/user-attachments/assets/c6b3d6e2-89b2-4acb-856d-a0c5327d2cf5)

**Comment by Mustachedom** [comment]
Oh you're on an outdated version, I highly recommend installing fresh from the green code button on md-drugs git page a lot more functionality and bug fixes

**Comment by callums18** [comment]
oh ok ill try it thank you

**Comment by callums18** [comment]
i just put the new one in and still nothing in return

**Comment by callums18** [comment]
its all of the start processes not sure why its probably me

**Comment by jokernights** [comment]
I also had this same issue but i was able to find an error each time i tried to process leaf it would go through the motions and give nothing in return.  and each one of these are each time i tried.
![image](https://github.com/user-attachments/assets/47a78b1f-f483-47ee-8643-6dc9fd91b9cf)

**Comment by Mustachedom** [comment]
That's because you didn't follow the readme and make the tier system

**Comment by jokernights** [comment]
> That's because you didn't follow the readme and make the tier system

Ok, I can say that I did miss this part 
![image](https://github.com/user-attachments/assets/78a83357-5606-4e9f-873e-2404cb387233)

but where do i search for this at? it doesn't really say. Sorry I am still in the learning process of all of this :)

**Comment by Mustachedom** [comment]
go to the config of qb-core and search metadata, underneath armor = 0, add this

 	lsd = 0,
        coke = 0,
        heroin = 0,
	dealerrep = 0,

**Comment by jokernights** [comment]
> lsd = 0,
>     coke = 0,
>     heroin = 0,
> dealerrep = 0,

ok so just like this? 
![image](https://github.com/user-attachments/assets/27edae45-a461-4e93-bd27-170b4016345e)

Also is there anything i have to do with ps-adminmenu like it says for qb-adminmenu?

**Comment by Mustachedom** [comment]
No if you use ps admin menu you're good! Qb admin has a feature to teleport you to a dealer, but it's 10000% not necessary. Yes the metadata looks good. Restart the server and you should be on your war to a drug lord

**Comment by jokernights** [comment]
> No if you use ps admin menu you're good! Qb admin has a feature to teleport you to a dealer, but it's 10000% not necessary. Yes the metadata looks good. Restart the server and you should be on your war to a drug lord

Thank you so much for the quick reply and the help. I'm excited :)

**Comment by jidennison91** [comment]
i dont see npc when i use coke burner for sell
