### ISSUE TITLE
No check if cops

### ISSUE THREAD

**Issue by madalton** [Mustachedom/md-drugs#50]
on client/cornerselling 

if not GetCops(QBConfig.MinimumDrugSalePolice) in RegisterNetEvent('md-drugs:client:cornerselling', function()

replace by if not GetCops(Config.PoliceCount)

Bye

**Comment by Mustachedom** [comment]
This is correct not an issue

**Comment by madalton** [comment]
yes i dont see qbdrugsrewrite. I m sorry
