### ISSUE TITLE
Price for selling

### ISSUE THREAD

**Issue by madalton** [Mustachedom/md-drugs#51]
in client/cornerselling : function Cornersell()

when check price :  

local table = QBConfig.DrugsPrice[item]
local price = math.random(table['min'], table['max'] ) * bagAmount

QBConfig.DrugsPrice is not define. in config you have : 
Config.Wcoke =  { min = 20, max = 60} -- pricings per item
Config.Wcrack = { min = 20, max = 60}
Config.Wlsd = { min = 20, max = 60}
Config.WXTC = { min = 20, max = 60}

i propose : 

--local table = QBConfig.DrugsPrice[item]
--local price = math.random(table['min'], table['max'] ) * bagAmount
local price = math.random(20,60) * bagAmount

bye

**Comment by Mustachedom** [comment]
That’s for a different feature cornerselling utilizes callbacks for calls from qbdrugsrewrite.lua

**Comment by madalton** [comment]
oh yes i m sorry

**Comment by sabotage93thctv** [comment]
where do you change the prices as its not so clear bud :)
