### ISSUE TITLE
Coke Process 

### ISSUE THREAD

**Issue by ColeGaming** [Mustachedom/md-drugs#53]
Its allowing to create the drugs the process but its not giving the final product to us and i used QS-inventory do you know how to fix this

**Comment by trippyturtle02** [comment]
has anyone found a solve to this i am having the same issue

**Comment by trippyturtle02** [comment]
> Its allowing to create the drugs the process but its not giving the final product to us and i used QS-inventory do you know how to fix this

Has anyone found a out how to solve this?

**Comment by Mustachedom** [comment]
i dont use nor want to learn how qs does things,
