### ISSUE TITLE
multiple errors when trying to use ox_target

### ISSUE THREAD

**Issue by wandomity** [Mustachedom/md-drugs#54]
i get multiple errors when using ox_target

![image](https://github.com/user-attachments/assets/bba989dd-b9a4-4fda-9279-3fc09c3c8273)

i honestly don't know why but if it's me doing smth wrong i would love to know so i can fix it

**Comment by wandomity** [comment]
and yes i do have config.oxtarget = true

**Comment by Mustachedom** [comment]
use older version of ox_target in releases, they dropped qb-comaptability so any script that uses those exports will break, ill be working on a push that has everything fully converted for qb/ox target and adding support for devyn-interact

**Comment by wandomity** [comment]
using a older version of ox_target does seem to work, however cocaine still doesn't, as far as i've been able to see, that is the only thing still not working

![image](https://github.com/user-attachments/assets/5b015558-314d-4f64-9a17-1398339a4eac)

**Comment by Mustachedom** [comment]
fixed in new update
