### ISSUE TITLE
Drying weed does not work

### ISSUE THREAD

**Issue by R3dNeckG** [Mustachedom/md-drugs#55]
Using ox target (older version for qb compatibility). When trying to hang it, I can see where the targets are, however I do not get the prompt. When I restart the script, I do see:

script:ox_target No entity with id '0' exists. 
![md-drugs](https://github.com/user-attachments/assets/4ae07055-a2a3-4582-b622-d78b906943cc)

**Comment by Mustachedom** [comment]
Outdated version
