### ISSUE TITLE
Corner Selling

### ISSUE THREAD

**Issue by JaiC1217** [Mustachedom/md-drugs#9]
Can't seem to get the drug selling to work after testing out each location

**Comment by MysticKillerBear** [comment]
errors?

**Comment by JaiC1217** [comment]
I see one from my shops that's about all

**Comment by JaiC1217** [comment]
New to coding and just found a few errors in my f8 my apologies.

**Comment by c-four77** [comment]
Download the dependencies in Readme u are missing the ox_lib

**Comment by JaiC1217** [comment]
Thanks man i did install all the needed resources but looks like i put them directly in [qb] instead of its own directory

**Comment by JaiC1217** [comment]
Appreciate it
